# vim: set et ts=2 sw=2 :
language: bash
services: docker

env:
  matrix:
  - RELEASES=latest
  - RELEASES=cli
  - RELEASES=fpm
  - RELEASES=apache

  global:
  - secure: odrak2D/T/TAH49Z/+7ivKGbgOr6pEDbXLdCH83yE+urTQTnalYcn+M174R4z35e3KeRnziC+5Y7NS6lXFcZ3e4rb1nsRAMbaVS+HrzqhtNYRIlG2+H8orjUMjEaDdAvx5yzPnIEBaGpe6qMUBIwmMyDeDvcu4GGTmQ2vjvQYTuG/BtX9bMYtE9hbHNoyC09FfWuOOiPtFYBJjFK5c/HcdEGrSK+veJh8SX+/jsLXjEPxRg/C98FjpPbkERvxVd5BUKzhzU9+XYnHAdjGtKMBGabxJPrVhn0EYsGwtuudZr4Ciu26hy+7IGqIva0RWhhUhz4SaQDnIPmfoQrHORgjhnJ4SojkiGOZ3WfyUC4hfhV6ljd55MVjGtBYmsHjx8TVXV2gd2Gy+yXS11zoi/KoYW3JeQ0Rm53P5cxg3lzqE2fywKpFEmflhm4L6kpfHwBkc4z1j06eqHovl73IgI4GESMrmkYeh4mkzkaQvPlsB6qTkbDcnpJF8O5RbPByaqxWVRjJQvMXbhMkgRuEV/0DzpcyG7vuJi1rnwWq1iG8wYSPvwPbifmFtY4AdEQmIJDmhMxyrjhgkxLzDCopJXQxwoY7Y4lVXL9JgEwbUKsutoehZ5bTJ2BoYbE/aoKeyZrZ7WRGrzxHVUxPWaZ7eRzNdWwtC083JikmHiuCrQBCTs=
  - secure: HJx6PCABKoAuJrRHUn6cAkwtBPfL6Leujevob4ykSkJQnMlh+VFyXVE65Dti5X7ZbZuNcnHpU8AN362V46YOJWWtChEH8eAH0hJze3JX6CWsAbOCjySFX7FJDQcXrx3TeOqnyw1O7QjYwuJKTIvRcQXCr/Z862aYizSVaHs1MRZKU99rcKLNzbMmpgyWa4PFSGxuEB3YVblxbkfD9ZBF/zJcqzlZ2bd72cSWs1/A/dMVAWMZnvBm41eJpweRoVk6qmatDd6y+urXX1F270Bzwn9Wsp5d/29ipvFqt1PSdBocYcK1cxXsg1z90GqzrIdoEla+nryJ38rPj3YB1nvW7p+NRWBEsHY5oC/rxfWg2cStnQaz2RJgCidfl2cHZJ15kkMVJ0iUnUQZAg20ycjKK2Mk3jcY3FibHBiHQrnE5h2ROtQd3pyZQ3HWEeVgubrp4xrZaMwmPBih2uUe5QVy6gC3R1UUAgdvpIztkdUmR0SFZ549pDghYPE2wqvLmSPwpOVoQd5GYEnfC7MY4+f/nXVAb6QnTZvR2qm5sAJDxuYVaGKSXwP7Pn7Ugf6JSjFeDurhalIKHo8zIFvCRWnJI3PTj9+MY6Duw5zeBQdynR2GxF5rfEgPCWcDFWKhct3LQudJrD9SbUXrV9CgqxphaxNHE23EujMnvQW8a7i5bQ8=

addons:
  apt:
    packages:
    - curl
    - jq

before_script:
  - ./docker-configure

script:
  - ./docker-build

after_script:
  - docker images

deploy:
  provider: script
  script: ./docker-push
  on:
    branch: master
